2020-08-01 18:27:22,688 ERROR: Exception on /mywords [GET] [in /Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/macbook/lang/flask_web_app/app/routes.py", line 54, in mywords
    words = current_user.languages[0].words.paginate(
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/sqlalchemy/orm/dynamic.py", line 323, in __getitem__
    return self._clone(sess).__getitem__(index)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3154, in __getitem__
    return list(self[item : item + 1])[0]
IndexError: list index out of range
2020-08-01 18:28:27,985 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-08-01 18:31:37,334 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-08-01 18:34:46,334 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-08-01 18:37:07,497 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-08-01 20:11:55,212 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-08-01 20:12:12,905 ERROR: Exception on /register [GET] [in /Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/macbook/lang/flask_web_app/app/routes.py", line 40, in register
    form = RegistrationForm()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/wtforms/form.py", line 268, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/wtforms/form.py", line 51, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/wtforms/meta.py", line 27, in bind_field
    return unbound_field.bind(form=form, **options)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/wtforms/fields/core.py", line 376, in bind
    return self.field_class(*self.args, **kw)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/wtforms/fields/core.py", line 473, in __init__
    super(SelectField, self).__init__(label, validators, **kwargs)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/wtforms/fields/core.py", line 442, in __init__
    super(SelectFieldBase, self).__init__(label, validators, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'coerse'
2020-08-01 20:13:01,092 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-08-01 20:13:09,335 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-08-01 20:13:14,211 ERROR: Exception on /register [GET] [in /Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/macbook/lang/flask_web_app/app/routes.py", line 41, in register
    form.language.choices = [(language.id, language.language) for language in Language.query.all()]
AttributeError: 'RegistrationForm' object has no attribute 'language'
2020-08-01 20:15:12,942 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-08-01 20:21:05,039 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
2020-08-01 20:21:30,560 ERROR: Exception on /register [POST] [in /Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/site12/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/macbook/lang/flask_web_app/app/routes.py", line 43, in register
    user = User(username = form.username.data, email=form.email.data, language=form.language.data)
AttributeError: 'RegistrationForm' object has no attribute 'language'
2020-08-01 20:22:17,611 INFO: Lang startup [in /Users/macbook/lang/flask_web_app/app/__init__.py:32]
